// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmhexijzsndsdeqllclt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaGV4aWp6c25kc2RlcWxsY2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjY3MDUsImV4cCI6MjA2Mzk0MjcwNX0.Cbt4dYT3HhyHwRraaTyrWSd0U_L_QiNTLuHzOsbIdxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);