// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// In Vite, environment variables are exposed with import.meta.env instead of process.env
// And they need to start with VITE_ prefix in the .env file
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xmhexijzsndsdeqllclt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtaGV4aWp6c25kc2RlcWxsY2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjY3MDUsImV4cCI6MjA2Mzk0MjcwNX0.Cbt4dYT3HhyHwRraaTyrWSd0U_L_QiNTLuHzOsbIdxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);